name: Client Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_client:
    name: Build client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    strategy:
      martrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client:
              - 'client/**'  
        uses: action/setup-node@v3
      - name: install modules
        if: steps.filter.outputs.client == 'true'
        run: npm install
      - name: build project
        if: steps.filter.outputs.client == 'true'
        run: npm build
      - name: tests
        if: steps.filter.outputs.client == 'true'
        run: npm test